name: formularacing
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+31

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  shared_preferences: ^2.2.2
  #uuid: ^4.0.0

  flutter_math_fork: ^0.7.2
  flutter_html: ^3.0.0
  google_fonts: ^6.3.1
  audioplayers: ^6.5.0
  #flutter_svg: ^2.0.0+1
  #cupertino_icons: ^1.0.8
  firebase_core: ^4.3.0 # Official latest stable
  firebase_database: ^12.1.1 # Official latest stable
  #cloud_firestore: ^4.14.0 # Official latest stable
  firebase_auth: ^6.1.3
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.1.2
  encrypt: ^5.0.1
  provider: ^6.0.5
  confetti: ^0.8.0
  sqflite: ^2.3.3      
  path: ^1.9.0
  lottie: ^3.3.1
  characters: ^1.4.0
  flutter_svg: ^2.2.3
  model_viewer_plus: ^1.8.0
  rive: ^0.14.0-dev.8
  url_launcher: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:

    - assets/sounds/correct.mp3
    - assets/sounds/wrong.mp3
    - assets/sounds/pop.wav
    - assets/logo.png
    - assets/pandaai/eat.json
    - assets/pandaai/hi.json
    - assets/pandaai/meditate.json
    - assets/pandaai/sleep.json
    - assets/pandaai/talk.json
    - assets/pandaai/bamboo_full.png
    - assets/pandaai/bamboo_low.png
    - assets/pandaai/friendGame.riv
    - assets/pandaai/soloGame.riv


    - assets/formulas/11/center_of_mass.aes
    - assets/formulas/11/circular_motion.aes
    - assets/formulas/11/elasticity.aes
    - assets/formulas/11/fluids.aes
    - assets/formulas/11/gravitation.aes
    - assets/formulas/11/kinematics.aes
    - assets/formulas/11/kinetic_theory.aes
    - assets/formulas/11/laws_of_motion.aes
    - assets/formulas/11/rotational_motion.aes
    - assets/formulas/11/shm.aes
    - assets/formulas/11/thermodynamics.aes
    - assets/formulas/11/units_and_dimensions.aes
    - assets/formulas/11/vectors.aes
    - assets/formulas/11/waves.aes
    - assets/formulas/11/work_power_energy.aes
    - assets/formulas/12/ac.aes
    - assets/formulas/12/capacitors.aes
    - assets/formulas/12/current_electricity.aes
    - assets/formulas/12/electrostatics.aes
    - assets/formulas/12/em_waves.aes
    - assets/formulas/12/emi.aes
    - assets/formulas/12/magnetism.aes
    - assets/formulas/12/dual_nature_of_light.aes
    - assets/formulas/12/atoms.aes
    - assets/formulas/12/nuclei.aes
    - assets/formulas/12/x_rays.aes
    - assets/formulas/12/ray_optics.aes
    - assets/formulas/12/semiconductors.aes
    - assets/formulas/12/wave_optics.aes
    - assets/formulas/full_syllabus_online_play_chemistry.aes
    - assets/formulas/full_syllabus_online_play_maths.aes
    - assets/formulas/full_syllabus_online_play.aes
    - assets/formulas/12/solid_state.aes
    - assets/formulas/12/3d_geometry.aes
    - assets/formulas/11/chemical_equilibrium.aes
    - assets/formulas/11/ellipse.aes
    - assets/formulas/12/definite_integrals.aes
    - assets/formulas/12/indefinite_integrals.aes
    - assets/formulas/12/electrochemistry.aes
    - assets/formulas/11/parabola.aes




      # images
    - assets/images/11th/Vectors/
    - assets/images/11th/units_and_dimensions/
    - assets/images/11th/kinematics/
    - assets/images/11th/work_power_energy/
    - assets/images/11th/center_of_mass/
    - assets/images/11th/laws_of_motion/
    - assets/images/11th/circular_motion/
    - assets/images/11th/Rotational_Motion/
    - assets/images/11th/gravitation/
    - assets/images/11th/elasticity/
    - assets/images/11th/fluids/
    - assets/images/11th/shm/
    - assets/images/11th/waves/
    - assets/images/11th/thermodynamics/
    - assets/images/11th/kinetic_theory/
    - assets/images/12th/Electrostatics/
    - assets/images/12th/capacitors/
    - assets/images/12th/current_electricity/
    - assets/images/12th/magnetism/
    - assets/images/12th/emi/
    - assets/images/12th/ac/
    - assets/images/12th/ray_optics/
    - assets/images/12th/wave_optics/
    - assets/images/12th/dual_nature_of_light/
    - assets/images/12th/atoms/
    - assets/images/12th/nuclei/
    - assets/images/12th/xrays/
    - assets/images/12th/semiconductors/
    - assets/images/12th/em_waves/
    - assets/images/12th/solid_state/
    - assets/images/12th/3d_geometry/
    - assets/images/11th/ellipse/
    - assets/images/11th/parabola/
    - assets/icon/

dependency_overrides:
  path_drawing: ^1.0.1
