name: formularacing
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  shared_preferences: ^2.2.2
  #uuid: ^4.0.0

  flutter_math_fork: ^0.7.2
  flutter_html: ^3.0.0
  google_fonts: ^6.2.1
  audioplayers: ^5.2.0
  #flutter_svg: ^2.0.0+1
  #cupertino_icons: ^1.0.8
  firebase_core:  ^2.29.0 # Official latest stable
  firebase_database: ^10.5.3 # Official latest stable
  #cloud_firestore: ^4.14.0 # Official latest stable
  firebase_auth: ^4.19.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/formulas/full_syllabus_online_play.json
    - assets/sounds/correct.mp3
    - assets/sounds/wrong.mp3
    - assets/logo.png
    # Class 11
    - assets/formulas/11/units_and_dimensions.json
    - assets/formulas/11/kinematics.json
    - assets/formulas/11/vectors.json
    - assets/formulas/11/laws_of_motion.json
    - assets/formulas/11/circular_motion.json
    - assets/formulas/11/work_power_energy.json
    - assets/formulas/11/center_of_mass.json
    - assets/formulas/11/rotational_motion.json
    - assets/formulas/11/gravitation.json
    - assets/formulas/11/elasticity.json
    - assets/formulas/11/fluids.json
    - assets/formulas/11/thermodynamics.json
    - assets/formulas/11/kinetic_theory.json
    - assets/formulas/11/shm.json
    - assets/formulas/11/waves.json

    # Class 12
    - assets/formulas/12/electrostatics.json
    - assets/formulas/12/capacitors.json
    - assets/formulas/12/current_electricity.json
    - assets/formulas/12/magnetism.json
    - assets/formulas/12/emi.json
    - assets/formulas/12/ac.json
    - assets/formulas/12/em_waves.json
    - assets/formulas/12/ray_optics.json
    - assets/formulas/12/wave_optics.json
    - assets/formulas/12/modern_physics.json
    - assets/formulas/12/semiconductors.json
    # full syllabus




      # images
    - assets/images/11th/Vectors/
    # - assets/images/11th/units_and_dimensions/
    - assets/images/11th/kinematics/
    - assets/images/11th/work_power_energy/
    - assets/images/11th/center_of_mass/
    - assets/images/11th/laws_of_motion/
    - assets/images/11th/circular_motion/
    - assets/images/11th/Rotational_Motion/
    - assets/images/11th/gravitation/
    - assets/images/11th/elasticity/
    - assets/images/11th/fluids/
    - assets/images/11th/shm/
    - assets/images/11th/waves/
    - assets/images/11th/thermodynamics/
    - assets/images/11th/kinetic_theory/
    - assets/images/12th/Electrostatics/
    - assets/images/12th/capacitors/
    #- assets/images/12th/current_electricity/
    - assets/images/12th/magnetism/
    - assets/images/12th/emi/
    #- assets/images/12th/ac/
    - assets/images/12th/ray_optics/
    #- assets/images/12th/wave_optics/
    - assets/images/12th/modern_physics/
    #- assets/images/12th/semiconductors/
    #- assets/images/12th/em_waves/
    - assets/icon/

dependency_overrides:
  path_drawing: ^1.0.1
